name: cred_pal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^3.2.0
  go_router: ^17.0.1
  flutter_svg: ^2.2.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.12.0
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/

  
  fonts:
    - family: Axiforma
      fonts:
        - asset: assets/fonts/axiforma/Axiforma-Thin.ttf
        - asset: assets/fonts/axiforma/Axiforma-Thinitalic.ttf
          weight: 100
        - asset: assets/fonts/axiforma/Axiforma-Light.ttf
        - asset: assets/fonts/axiforma/Axiforma-Lightitalic.ttf
          weight: 200
        - asset: assets/fonts/axiforma/Axiforma-Book.ttf
        - asset: assets/fonts/axiforma/Axiforma-Bookitalic.ttf
          weight: 300
        - asset: assets/fonts/axiforma/Axiforma-Regular.ttf
        # - asset: assets/fonts/axiforma/Axiforma-Regularitalic.ttf
          weight: 400
        - asset: assets/fonts/axiforma/Axiforma-Medium.ttf
        - asset: assets/fonts/axiforma/Axiforma-Mediumitalic.ttf
          weight: 500
        - asset: assets/fonts/axiforma/Axiforma-SemiBold.ttf
        - asset: assets/fonts/axiforma/Axiforma-SemiBolditalic.ttf
          weight: 600
        - asset: assets/fonts/axiforma/Axiforma-Bold.ttf
        - asset: assets/fonts/axiforma/Axiforma-Bolditalic.ttf
          weight: 700
        - asset: assets/fonts/axiforma/Axiforma-ExtraBold.ttf
        - asset: assets/fonts/axiforma/Axiforma-ExtraBolditalic.ttf
          weight: 800
        - asset: assets/fonts/axiforma/Axiforma-Black.ttf
        - asset: assets/fonts/axiforma/Axiforma-Blackitalic.ttf
          weight: 900
        - asset: assets/fonts/axiforma/Axiforma-Heavy.ttf
        - asset: assets/fonts/axiforma/Axiforma-Heavyitalic.ttf
          weight: 900

    - family: Avenir
      fonts:
      - asset: assets/fonts/Avenir/Avenir-Book.ttf
        weight: 300
      - asset: assets/fonts/Avenir/Avenir-BookOblique.ttf
        weight: 300
      - asset: assets/fonts/Avenir/Avenir-Roman.ttf
        weight: 400
      - asset: assets/fonts/Avenir/Avenir-Oblique.ttf
        weight: 400
      - asset: assets/fonts/Avenir/Avenir-Medium.ttf
        weight: 500
      - asset: assets/fonts/Avenir/Avenir-MediumOblique.ttf
        weight: 500
      - asset: assets/fonts/Avenir/Avenir-Light.ttf
        weight: 200
      - asset: assets/fonts/Avenir/Avenir-LightOblique.ttf
        weight: 200
      - asset: assets/fonts/Avenir/Avenir-Heavy.ttf
        weight: 800
      - asset: assets/fonts/Avenir/Avenir-HeavyOblique.ttf
        weight: 800
      - asset: assets/fonts/Avenir/Avenir-Black.ttf
        weight: 900
      - asset: assets/fonts/Avenir/Avenir-BlackOblique.ttf
        weight: 900


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
  # flare_flutter: true
  # rive: true